name: my_notes
description: A new Flutter project.
publish_to: "none"
version: 1.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore:
  equatable: ^2.0.5
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  path: ^1.8.3
  path_provider: ^2.0.15
  share_plus: ^7.0.2
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true
